### ISSUE TITLE
Unexpected behavior for of_box() and to_box() for 0-dim domain elements

### ISSUE THREAD

**Issue by ezaffanella** [antoinemine/apron#58]
It seems that box and polka domains behave differently when importing/exporting a 0-dimensional abstract value as an array of intervals (using ap_abstract0_of/to_box). The following program seems to witness a mismatch:

```
#include <stdio.h>
#include <stdlib.h>

#include <ap_global0.h>
#include <box.h>
#include <pk.h>

ap_manager_t* box_man;
ap_manager_t* pk_man;

int main() {
  ap_manager_t* box_man = box_manager_alloc();
  ap_manager_t* pk_man = pk_manager_alloc(false);

  ap_interval_t** itvs0 = ap_interval_array_alloc(1);

  ap_abstract0_t* box0 = ap_abstract0_of_box(box_man, 0, 0, itvs0);
  bool box0_is_bottom = ap_abstract0_is_bottom(box_man, box0);
  bool box0_is_top = ap_abstract0_is_top(box_man, box0);
  printf("box0 is bottom = %i, box0 is top = %i\n\n", box0_is_bottom, box0_is_top);

  ap_abstract0_t* pk0 = ap_abstract0_of_box(pk_man, 0, 0, itvs0);
  bool pk0_is_bottom = ap_abstract0_is_bottom(pk_man, pk0);
  bool pk0_is_top = ap_abstract0_is_top(pk_man, pk0);
  printf("pk0 is bottom = %i, pk0 is top = %i\n\n", pk0_is_bottom, pk0_is_top);

  ap_interval_t** itvs1 = ap_abstract0_to_box(pk_man, pk0);
  ap_abstract0_t* box1 = ap_abstract0_of_box(box_man, 0, 0, itvs1);
  bool box1_is_bottom = ap_abstract0_is_bottom(box_man, box1);
  bool box1_is_top = ap_abstract0_is_top(box_man, box1);
  printf("box1 is bottom = %i, box1 is top = %i\n\n", box1_is_bottom, box1_is_top);
}

```

It prints:

$ ./bug 
box0 is bottom = 1, box0 is top = 0

pk0 is bottom = 0, pk0 is top = 1

box1 is bottom = 1, box1 is top = 0

Am I missing anything obvious (e.g., violating a library precondition)?

**Comment by antoinemine** [comment]
Hi. Thanks for the report!

0-dimensional abstract elements can be top or bottom. newpolka and octagons assume that `of_box` for 0-dimensional elements is top, not bottom. MR #63 should fix the box domain to behave the same way. Would that be OK for you?

It is a corner case, but it is still important as it is legit and useful to build an abstract element by adding variables to an empty environment.

**Comment by ezaffanella** [comment]
Hi Antoine.

I think that MR https://github.com/antoinemine/apron/pull/63 is enough to fix the behavior of function(s) of_box.

However, I still have some doubts regarding functions to_box when applied to a 0-dim *bottom* box/poly; it seems to produce a zero-length array of intervals and, if you feed this back to function of_box, you will obtain a 0-dim *top* element (have not really tried it, please recheck). I see two different workarounds:
  a) functions to_box should return a null pointer if applied to a 0-dim bottom abstract element
  b) functions to_box should have as a precondition that the element is not bottom
What do you think?

**Comment by antoinemine** [comment]
Hi Enea,

For n-dim boxes with n > 0, to_box fills the vector with bottom intervals. You can then feed it back to of_box to get a bottom abstract elements, and it works well. For n = 0, of course, it is not possible, we have only a single 0-sized vector, and it cannot represent both bottom and top...
I'm not liking the idea of returning NULL. At least returning a 0-dim top is sound and safe! I'd rather document the special 0-dim case to say that it returns a top 0-dim element. If needed, it is possible to test whether the 0-dim abstract element is bottom or not before calling to_box.

**Comment by ezaffanella** [comment]
I agree that the null pointer option looks dangerous. Fine with the other option.
Thanks.
